spring.application.name=auth

jwt.secret=gah6h6sHCiC0nEnAHzq3djiFmfdj/Kh57Q19W1u2mPY=
logging.level.org.springframework.security=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true